spring:
  application:
    name: library-book-service
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      properties:
        spring:
          json:
            type:
              mapping: "borrowedBookNotificationDto:org.vitalii.fedyk.librarybookservice.dto.BorrowedBookNotificationDto"

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true
server:
  port: ${PORT}
